#-*- coding: utf-8 -*-

TextWidget:

<TextWidget>:
    BoxLayout:
        orientation: 'vertical'
        size: root.size

        BoxLayout:
            size_hint_y: 0.1

            Button:
                font_size: 34
                text: "connect"
                on_press: root.connect_to_server()

            Label:
                font_size: 20
                text: root.debug

        # ラベル
        Label:
            size_hint_y: 0.6 # 50% display
            id: label1
            font_size: 68
            text: root.text  # get the root(TextWidget) value 
            color: root.color

        BoxLayout:
            size_hint_y: 0.4 # 40% display
            padding: 20,30,20,10
            Button:
                id: button1
                on_press: root.buttonClicked1()  # call the python code when clicked
                on_release: root.buttonRelease1()
                Image:
                    source: "./images/left.png"
                    center_x: self.parent.center_x 
                    center_y: self.parent.center_y 
                    size:100, 100

            Button:
                id: button2
                on_press: root.buttonClicked2() 
                on_release: root.buttonRelease2()
                Image:
                    source: "./images/forward.png"
                    center_x: self.parent.center_x 
                    center_y: self.parent.center_y 
                    size:100, 100
            Button:
                id: button3
                on_press: root.buttonClicked3()
                on_release: root.buttonRelease3()
                Image:
                    source: "./images/backward.png"
                    center_x: self.parent.center_x 
                    center_y: self.parent.center_y 
                    size:100, 100
            Button:
                id: button4
                on_press: root.buttonClicked4()
                on_release: root.buttonRelease4()
                Image:
                    source: "./images/right.png"
                    center_x: self.parent.center_x 
                    center_y: self.parent.center_y 
                    size:100, 100
